config/routes.rb
Rails.application.routes.draw do

  scope path: "asset-directory" do
    resources :assets, as: 'assets', path: 'all'
    get 'items', to: 'assets#items', as: 'items', path: 'items'
  end

  resources :categories
  resources :employees
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  resources :welcome
  resources :login
  resources :loans

  get "user/login"
  get "user/sign_up"

  root 'assets#index'
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  has_many :assets
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  def index
    @employees = Employee.all
  end

  def show
  end

  def new
    @employee = Employee.new
  end

  def edit
  end

  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_employee
      @employee = Employee.find(params[:id])
    end

    def employee_params
      params.require(:employee).permit(:first_name, :last_name, :department)
    end
end

app/helpers/employee_helper.rb
module EmployeeHelper
end

app/views/employees/_form.html.slim
= form_for @employee do |f|
  - if @employee.errors.any?
    #error_explanation
      h2 = "#{pluralize(@employee.errors.count, "error")} prohibited this employee from being saved:"
      ul
        - @employee.errors.full_messages.each do |message|
          li = message

  .field
    | First Name:
    = f.text_field :first_name
  .field
    | Last Name:
    = f.text_field :last_name
  .field
    | Department
    = f.text_field :department
  .actions = f.submit

app/views/employees/edit.html.slim
.container
	h1 Editing employee

	.form
		= render 'form'

		= link_to 'Show', @employee, class: 'btn btn-primary'
		= link_to 'Done', employees_path, class: 'btn btn-primary'

app/views/employees/index.html.slim
= render "shared/asset_nav"
.container
  .page-header
    h1 Employees

  .float-left
    table
      thead
        tr
          th No.
          th First Name
          th Last Name
          th Department
          th

      tbody
        - @employees.each do |employee|
          tr
            td = employee.id
            td = employee.first_name
            td = employee.last_name
            td = employee.department
            td
              = link_to 'view', employee_path(employee.id), class: 'btn btn-primary'
              = link_to 'Edit', edit_employee_path(employee), class: 'btn btn-primary'
              = link_to 'Delete', employee, data: { :confirm => 'Are you sure?' }, :method => :delete, class: 'btn btn-primary'

    br

    = link_to 'New Employee', new_employee_path, class: 'btn btn-primary'

  .float-right
    h2 Search Bar
    form.search-form
      | Enter Search item here:
      br
      input name="username" type="text"
      br
      input.button onclick="alert('Search')" type="button" value="Search"

app/views/employees/new.html.slim
.container
  h1 New Employee
  
  .form
    = render 'form'
    = link_to 'Back', employees_path, class: 'btn btn-primary'

app/views/employees/show.html.slim
.page-header
  h1 Employee Details
.container
  p#notice = notice

  .form
    p
      strong First Name:
      = @employee.first_name
    p
      strong Last Name:
      = @employee.last_name
    p
      strong Department:
      = @employee.department

    = link_to 'Edit', edit_employee_path(@employee), class: 'btn btn-primary'
    = link_to 'Done', employees_path, class: 'btn btn-primary'