config/routes.rb
Rails.application.routes.draw do

  scope path: "asset-directory" do
    resources :assets, as: 'assets', path: 'all'
    get 'items', to: 'assets#items', as: 'items', path: 'items'
  end

  resources :categories
  resources :employees
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  resources :welcome
  resources :login
  resources :loans

  get "user/login"
  get "user/sign_up"

  root 'assets#index'
end

app/views/shared/_asset_nav.html.slim
div class="asset-nav"
  ul class="asset-nav-bar"
    li class="label-asset"
      | Assets
    li
      = link_to "All Assets", assets_path, class: 'btn btn-info'

    table
    tbody
      - Category.all.each do |category|
        tr
          td = link_to category.name, items_path(category_param: category.id), class: 'btn btn-info'

app/views/shared/_asset_table.html.slim
.search-area
  | Search:
  input name="text" type="text" class="input-text-field"
  input.button onclick="alert('Search')" type="button" value="Search"
br
= link_to 'New Asset Item', new_asset_path, class: 'btn btn-primary'
= link_to 'Add Category', new_category_path, class: 'btn btn-primary'
br

.float-left
  table
    thead
      tr
        th Item model
        th Item description
        th Item price
        th Item attributes
        th Category
        th Assignee
        th

    tbody
      - @assets.each do |asset|
        tr
          td = asset.item_model
          td = asset.item_description
          td = asset.item_price
          td = asset.item_attributes
          td = asset.category.name
          td = asset.assignee
          td
            = link_to 'Show', asset, class: 'btn btn-primary'
            = link_to 'Edit', edit_asset_path(asset), class: 'btn btn-primary'
            = link_to 'Delete', asset, data: {:confirm => 'Are you sure?'}, :method => :delete, class: 'btn btn-primary'

app/views/shared/_footer.html.slim
.row
  .col-lg-12
    p Copyright &copy; Asset Manager 2015, Done by Daniel Steenberg

app/views/shared/_header.html.slim
head
    = stylesheet_link_tag    "application", media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag "application", 'data-turbolinks-track' => true
    = csrf_meta_tags

    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    meta name="viewport" content="width=device-width, initial-scale=1"
    meta name="description" content=""
    meta name="author" content=""

    title Asset Manager

app/views/shared/_nav.html.slim
nav class="navbar navbar-inverse navbar-fixed-top" role="navigation"
  .container
    .navbar-header
      button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
        span class="sr-only" Toggle navigation
          span class="icon-bar"
            span class="icon-bar"
              span class="icon-bar"

    .collapse.navbar-collapse#bs-example-navbar-collapse-1
      ul class="nav navbar-nav navbar-left"
        li
          a href="/welcome"Asset Manager

    .collapse.navbar-collapse#bs-example-navbar-collapse-1
      ul class="nav navbar-nav navbar-right"
        li
          a href="about.html"About

        li
          a href="contact.html"Contact

        li
          = link_to "Employees", employees_path

        li
          = link_to "All Assets", assets_path
        li
          = link_to "All Categories", categories_path
        li
          = link_to "Loaned Units", loans_path

        li.dropdown
          a href="#" class="dropdown-toggle" data-toggle="dropdown"
            ul class="dropdown-menu"
              li: a href="portfolio-1-col.html"1 Column Portfolio
              li: a href="portfolio-2-col.html"2 Column Portfolio
              li: a href="portfolio-3-col.html"3 Column Portfolio
              li: a href="portfolio-4-col.html"4 Column Portfolio
              li: a href="portfolio-item.html"Single Portfolio Item

        li.dropdown
          a href="#" class="dropdown-toggle" data-toggle="dropdown"
            ul class="dropdown-menu"
              li: a href="blog-home-1.html"Blog Home 1
              li: a href="blog-home-2.html"Blog Home 2
              li: a href="blog-post.html"Blog Post


        li class="dropdown"
          a href="#" class="dropdown-toggle" data-toggle="dropdown"
            ul class="dropdown-menu"
              li: a href="#"Add Employee
              li: a href="#"Update Employee
              li: a href="#"Delete Employee
    .collapse.navbar-collapse#bs-example-navbar-collapse-1
      ul class="nav navbar-nav navbar-right"
        li
        - if user_signed_in?
          = current_user.email
          = link_to "  Sign out", destroy_user_session_path, method: 'delete'
        - else
          = link_to "Sign up  ", new_user_registration_path
          = link_to "Sign in", new_user_session_path
        end
        / .navbar-collapse

        / .container