config/routes.rb
Rails.application.routes.draw do

  scope path: "asset-directory" do
    resources :assets, as: 'assets', path: 'all'
    get 'items', to: 'assets#items', as: 'items', path: 'items'
  end

  resources :categories
  resources :employees
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  resources :welcome
  resources :login
  resources :loans

  get "user/login"
  get "user/sign_up"

  root 'assets#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :assets
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def show
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to assets_path, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name)
    end
end

app/views/categories/_form.html.slim
= form_for @category, html: { multipart: true , class: 'form-horizontal' } do |f|
  - if @category.errors.any?
    #error_explanation
      h2 = "#{pluralize(@category.errors.count, "error")} prohibited this asset from being saved:"
      ul
        - @category.errors.full_messages.each do |message|
          li = message
  .form
    .field
      = f.label :name
      = f.text_field :name
    .actions
      = f.submit

app/views/categories/edit.html.slim
.page-header
  h1 Editing Category

= render 'form'

= link_to 'Show', @Category
'|
= link_to 'Back', category_path

app/views/categories/index.html.slim
= render "shared/asset_nav"
.container
  .page-header
    h1 All Categories

  .float-left
    table
      thead
        tr
          th Category
          th

      tbody
        - @categories.each do |category|
          tr
            td = category.name
            td
              = link_to 'Show', category, class: 'btn btn-primary'
              = link_to 'Edit', edit_category_path(category), class: 'btn btn-primary'
              = link_to 'Delete', category, data: {:confirm => 'Are you sure?'}, :method => :delete, class: 'btn btn-primary'
      = link_to 'New Category Item', new_category_path, class: 'btn btn-primary'

app/views/categories/new.html.slim
.page-header
  h1 New Category

= render 'form'

= link_to 'Back', categories_path

app/views/categories/show.html.slim
.page-header
  h1 Category Details
.container
  p#notice = notice

  .form
    p
      strong Item model:
      = @category.name

  br
    = link_to 'Edit', edit_category_path(@category), class: 'btn btn-primary'
    = link_to 'Done', categories_path, class: 'btn btn-primary'